language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - hhvm
script: phpunit
before_script: composer install
notifications:
email:
  - "molonlabetr@gmail.com"
  - "hasanerikan@creasoup.com"
  on_success: [always|never|change] # default: change
  on_failure: [always|never|change] # default: always